### ISSUE TITLE
pt chartset error

### ISSUE THREAD

**Issue by ygorgasparin** [marlonlom/timeago#1]
Hi Marlon, 

Nice library you have.

I have noted there is an error on "ml.timeago.aboutamonth" pt message.

I think change "m�s" to  "m\u00eas" should be work as well

Best,

**Comment by marlonlom** [comment]
The strange characters that appear in the texts have been fixed, not only in Portuguese, but also the other languages have been revised.

Regards,

**Comment by ygorgasparin** [comment]
Hi Marlon, 

You will release another version with this fix? 

Thank you

**Comment by marlonlom** [comment]
Hi,

Yes, i'll be releasing a new version, along with some other feats and improvements. Please stay tuned.

Regards,
