### ISSUE TITLE
Time ago does not work On android 6 and 7

### ISSUE THREAD

**Issue by BbosaH** [marlonlom/timeago#13]
I am using this Liibrary but it works only up to android 5.. what can i do it just keeps showing 'just now' for android 6 and 7 devices

**Comment by bernaferrari** [comment]
It works fine here on Android 7 and 8. Could you share the code that is not working?

**Comment by marlonlom** [comment]
Agree with @bernaferrari, could you share the code?  Btw, there is New version of the library

**Comment by marlonlom** [comment]
@BbosaH I've published a newer version of the library, would you check it out it your issue persists?

**Comment by marlonlom** [comment]
@BbosaH Hi, any comment on this? i've upgraded the lib.
