### ISSUE TITLE
No artifact built with last version (3.0.2)

### ISSUE THREAD

**Issue by tspoke** [marlonlom/timeago#16]
I cannot import your latest build with jitpack for version 3.0.2. 

See debug log here : 

https://jitpack.io/com/github/marlonlom/timeago/v3.0.2/build.log

I was able to import version 3.0.1 with success.

Thanks.

**Comment by marlonlom** [comment]
@tspoke I couldnt reproduce that you're mentioning here :worried:.
Tip: Recently, i've prepared v4.0.x, it can be downloaded and tested.
