### ISSUE TITLE
How to decrease the level of detail

### ISSUE THREAD

**Issue by farenza** [marlonlom/timeago#18]
I don't know how to change "a minute ago" or "a hour ago" to just "today"

**Comment by marlonlom** [comment]
@farenza mm, this is not intented to do (at least for me). The idea is to display a 'relative datetime' text according to presented timestamp.
¿Do you have a scenario for that -example, usecase- ?

**Comment by farenza** [comment]
I have a date format in sql (example: 02/10/2018)
so details of minutes, seconds and hours will be useless,
so I changed it to just today
but my relative date calculation is inaccurate
for example I had two days ago when it was a different day
here's my code
`public static String setRelativeDate(String tgl, String TAG){
        SimpleDateFormat first = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault());
        java.util.Date date = new Date();
        TimeAgoMessages messages = new TimeAgoMessages.Builder().defaultLocale().build();
        try{
            date = first.parse(tgl);
        }catch (ParseException e){
            e.printStackTrace();
        }

        //TODO: 2 days on future and 3 days on future have same name "within 2 days" and +1 day for future that is not accurate
        String timeAgo = TimeAgo.using(date.getTime(),messages);
        if      ((timeAgo.contains("ago") && timeAgo.contains("hours")) || timeAgo.contains("just now")){return "today";}
        else if (timeAgo.contains("within") && timeAgo.contains("hours")){return "tomorrow";}
        else if (timeAgo.contains("tomorrow")){return "within 2 days";}
        else{ return timeAgo;}
    }
`
hmm maybe there an option that i don't know yet?

**Comment by marlonlom** [comment]
i guess im closing thins because of your last commet about using timestamps :)
