### ISSUE TITLE
Can we have date in the future

### ISSUE THREAD

**Issue by olivierperez** [marlonlom/timeago#2]
I looked into the code, and i seen that dates in the future are not managed.
Can you please do this? I'm really intrested into this feature.

**Comment by marlonlom** [comment]
Hello,

Showing the dates of the future form, such as '_within 2 days_', had not been contemplated before, because it was emphasized to show information of dates of the form '_3 days ago_'. 

I'll keep this additional feature in mind for a new version, stay in touch.

Regards,

**Comment by olivierperez** [comment]
Hi, many thanks for the feature. I've seen the two commits:
840dd6eeb6acaef97c987ce2bd1e662c3ab41cac
4801a750e18ced901e4cf22cccb485f89f275ac0

I've also proposed you a Pull request that fixes the FR translation: https://github.com/marlonlom/timeago/pull/3

**Comment by marlonlom** [comment]
@olivierperez It's great!!! Thanks for review the FR translations :D
