### ISSUE TITLE
How to change a specific message 

### ISSUE THREAD

**Issue by yoboitel** [marlonlom/timeago#23]
Hi :)
Is is possible to custom a specific message ?
For exemple changing "x minutes ago" to just "x minutes" etc... ?

**Comment by hphl** [comment]
any news?

**Comment by marlonlom** [comment]
> any news?

Mmm, you can do so by using another methods, for example, using String.replace method. But, keep in mundo that the messages are relates to specific languages, so, its not a good idea (imho)

**Comment by cwbsl** [comment]
Some things are worded strangely in German and I would also like to fix some strings. Using replace functions is not going to be good since this would change the context.
Is there any way to override the strings?
