### ISSUE TITLE
How to only get "time ago" if it's in the same month

### ISSUE THREAD

**Issue by melatgenius** [marlonlom/timeago#30]
Is there a way to get "from" or "within" methods? for example , I only want the dates to show "time ago" if it's within the month?  not pass 30 days ago...

**Comment by marlonlom** [comment]
Hi @melatgenius 
The calculation thath checks if a date is within a month you can do so using the Calendar and Date clases provided by java/Kotlin.

An example of this (as a understood) could be this way:

```java
private String getTimeAgoWithinMonth(timeMillis:Long) {
  Calendar someCalendar = Calendar.getInstance();
  someCalendar.setTime(timeMillis);
  if (withinCurrentMonth(someCalendar)){ /*Here is that you can do for validate if a date is within current month*/
    return TimeAgo.using()
  } else {
    Throw new Exception("Some error for this");
  }  
}
```
The message here is that the dates validation you mentiones is not in the scope of the library. 

Regards, :)

**Comment by marlonlom** [comment]
it gets closed because this has been idle for some time
