### ISSUE TITLE
Can't find bundle for base name

### ISSUE THREAD

**Issue by calber** [marlonlom/timeago#31]
Im'getting this error on obfuscate (release) apk:

Caused by java.util.MissingResourceException: Can't find bundle for base name com.github.marlonlom.utilities.timeago.messages, locale en

is there a missing proguard rule too consider or else ?

**Comment by marlonlom** [comment]
Hi  @calber 

Did you add the library using gradle? or manually?

**Comment by marlonlom** [comment]
closed as it was fixed in recent versions...
