### ISSUE TITLE
Does timeago support translations? 

### ISSUE THREAD

**Issue by melatgenius** [marlonlom/timeago#32]
building an app that supports many different languages. wanted to use this library but realized that it might not support translation. does it?

**Comment by marlonlom** [comment]
Hi @melatgenius,

What do you mean by support translation?

The library has some language messages xml files that contains the traslation (you can check the src).

Could you give some context so it can be reviewed?

Regards,

**Comment by raghavsatyadev** [comment]
@marlonlom I actually tried some translations with Chinese (zh), Tamil (ta), Urdu (ur). properties file does not support their encodings. please try to move them to Strings file.
![image](https://user-images.githubusercontent.com/6176423/57566085-fb293e80-73e5-11e9-8441-8fc28ac99462.png)

try to use this library for local changing
https://github.com/akexorcist/Android-LocalizationActivity

**Comment by marlonlom** [comment]
@raghavsatyadev mm, you can try using UTF8 instead of 'windows-1252', that could generate some problems when executing the application.

**Comment by raghavsatyadev** [comment]
Actually I can't Studio in Windows 10 does not support UTF-8 in resources files. it's disabled. I got around the issue by converting all of them in unicode

**Comment by Moh09** [comment]
About translations, small mistake, in french it is missing an e to "a minute ago" ("il y a un minute", it's "une").

**Comment by marlonlom** [comment]
> Actually I can't Studio in Windows 10 does not support UTF-8 in resources files. it's disabled. I got around the issue by converting all of them in unicode

@raghavsatyadev  you men this? https://stackoverflow.com/questions/53694004/android-studio-doesnt-recognize-utf-8-encoding

**Comment by marlonlom** [comment]
> About translations, small mistake, in french it is missing an e to "a minute ago" ("il y a un minute", it's "une").

@Moh09 mmm, that was mentioned in another issue?

**Comment by marlonlom** [comment]
im closing this as it has no clarification about the issue.
