### ISSUE TITLE
Some texts in Arabic is misspelled. 

### ISSUE THREAD

**Issue by AbdAllahAbdElFattah13** [marlonlom/timeago#34]
For example:
```
ml.timeago.now=الان
ml.timeago.oneminute.past=منذ دقيقه
```
Should be:
```
ml.timeago.now=الآن
ml.timeago.oneminute.past=منذ دقيقة
```

**Comment by AbdAllahAbdElFattah13** [comment]
Created pr https://github.com/marlonlom/timeago/pull/35 to fix it!

**Comment by marlonlom** [comment]
I could not remember that PR #35 @AbdAllahAbdElFattah13  ... but, i've added the texts you mentioned. it will be released soon. :)

**Comment by AbdAllahAbdElFattah13** [comment]
@marlonlom You already merged it on Sep. 8 and released! :)
