### ISSUE TITLE
Misspelling in French

### ISSUE THREAD

**Issue by Nebneb** [marlonlom/timeago#36]
Hi ! Thanks a lot for this great library. 
Just to let you know, there's a misspelled pronoun in French : 

```
ml.timeago.oneminute.past=il y a un minute
```
Should be :

```
ml.timeago.oneminute.past=il y a une minute
```

("une" instead of "un")

Thank you in advance.

**Comment by marlonlom** [comment]
@Nebneb  Thanks for the comment, i've fixed this and will be released soon. :)
