### ISSUE TITLE
Please add support for weekAgo and monthAgo

### ISSUE THREAD

**Issue by PeriyaCC** [marlonlom/timeago#39]

**Comment by marlonlom** [comment]
Please @PeriyaCC, would you describe more about that WeekAgo and MonthAgo terms you said before?

**Comment by cbedoy** [comment]
I think month ago is already supported, probably I can help adding support for week ago, since I need it to.

**Comment by PeriyaCC** [comment]
Thanks for such awesome library..  It would be much better if u could add support for week**s** ago, month**s** ago and year**s** ago.

**Comment by marlonlom** [comment]
@cbedoy @PeriyaCC could you explain more in detail about that... i've faced the weeks and months variant since the beggining...

**Comment by Nikunj2505** [comment]
I am also looking for week ago update

**Comment by marlonlom** [comment]
@Nikunj2505 @cbedoy @PeriyaCC I've updated the unit tests and moved it to a test suite

**Comment by cbedoy** [comment]
Thanks

**Comment by marlonlom** [comment]
Upgraded version!! check the unit tests :)
