### ISSUE TITLE
MissingResourceExcetpion - Cant find bundle

### ISSUE THREAD

**Issue by IndianaSloan** [marlonlom/timeago#44]
Getting intermittent issues where the following exception is thrown:

```
java.util.MissingResourceException: Can't find bundle for base name com.github.marlonlom.utilities.timeago.messages, locale en_US
```
Currently using `v4.0.3`

**Comment by marlonlom** [comment]
Hi @IndianaSloan 
Are you using the locale 'en_US' for retrieving the messages? the languages are country-aware ...

**Comment by IndianaSloan** [comment]
@marlonlom yes, I was previously not defining the Locale as it appears to use device default Locale. However I was getting the same exception thrown except for `locale eb_GB` - again intermittent and not every time.

I switched to passing in an instance of `TimeAgoMessages` into the `using()` function and setting the Locale to `Locale.US` and getting the above reported exception

**Comment by marlonlom** [comment]
But have you tried using the two-digit language code?
in readme, i've shared an example using the language code for getting the messages ...

```kotlin
var localeBylanguageTag = Locale.forLanguageTag("en")
var messages = TimeAgoMessages.Builder().withLocale(localeBylanguageTag).build()
```

As i said before, the languages are country-aware, for example, in this case, you must get the locale for the english using the `Locale.forLanguageTag()` method/function.

**Comment by IndianaSloan** [comment]
I'll try this and let you know if it resolves the issue. But surely I
shouldn't be experiencing the crash when I use the default messages?

**Comment by marlonlom** [comment]
@IndianaSloan 
`
shouldn't be experiencing the crash when I use the default messages?
`
...
Not really,for that reason i tried the example with code before.

**Comment by marlonlom** [comment]
Since i did not get some feedback about the reported issue, im closing this one.
