### ISSUE TITLE
Errors occurred while build effective model ...

### ISSUE THREAD

**Issue by serenesensei** [marlonlom/timeago#45]
Log shows this message but the build completes successfully :

`Errors occurred while build effective model from C:\Users\username\.gradle\caches\modules-2\files-2.1\com.github.marlonlom\timeago\4.0.3\9f2ae963de80268c3fcab54f0d7313d983194e1a\timeago-4.0.3.pom:
    'modelVersion' must be one of [4.0.0] but is '4.0.3'. in com.github.marlonlom:timeago:4.0.3`

**Using :**
- TimeAgo: 4.0.3
- Gradle: gradle-7.0-rc-1
- Kotlin: 1.5.0-M1
- JDK: 16

**Comment by me-sleepy** [comment]
I see, this happens only in my spring boot project.  

Steps to reproduce:
1. Generate a bare bones project from [Spring Initializr](https://start.spring.io/) (Spring Boot 2.4.5 + Kotlin + Gradle + Java 16)
2. Add timeago-4.0.3 as a dependency.
3. Build the project.

**Comment by marlonlom** [comment]
@serenesensei  any update on this ? i did test it using a spring boot project in a work company and it worked.
