### ISSUE TITLE
Is it support chinese?

### ISSUE THREAD

**Issue by huhx** [marlonlom/timeago#51]
val locale = Locale.forLanguageTag("zh")
val messages = TimeAgoMessages.Builder().withLocale(locale).build()

println(TimeAgo.using(epochMilli, messages))

still the `en`

Looking forward to new version that include the `zh`

**Comment by marlonlom** [comment]
@huhx Hi,
Yes, it supports chinesse language, but, as you said, it not appear in `4.0.3` version, it will be included, along with other languages, in the newer version of the library.
The new version will be released soon, so stay tuned! :)
