### ISSUE TITLE
it always show 47 yrs ago

### ISSUE THREAD

**Issue by macin11** [marlonlom/timeago#9]
Don't know why it is showing 47years ago for every timestamp;

**Comment by KevadiyaK** [comment]
Hi,
 i am use this lib.
-> you have just use like **TimeAgo.using(([your timestamp] * 1000L), messages)**

**Comment by felangga** [comment]
same problem.
@KevadiyaK your solution not working on mine

**Comment by Ravslee** [comment]
Make sure you are passing the timestamp value. I had the similar issue, Found that the value I was passing was null.
